takeoff:        [0.0, 0.0, 1.0]

1st_square:     [0.0, 0.0, 1.0]

2nd_square_pre: [3.5, -1.35, 1.35]

2nd_square_end: [4.4, -1.35, 1.35]

car:            [6.29, 0.68, 1.0]

land:           [2.2, 0.0, 1.0]